sudo: required
services:
- docker
script:
# - full/ci.sh
- base/ci.sh
jobs:
  include:
    - stage: build
      script: make base
    - script: make full
    - stage: test
      script: make test-base
    - script: make test-full

notifications:
  slack:
    secure: I01kvX71vWivneJVHCN6vlSM4rFJU2Awi3uXn24ZtuAeFN1DCp+GLkRBzcVeRAKQcA3WYPemWbJgYPCkBfprl1gxcatCoBcey2Vv4cYyXOy62dgHDAyeD040VNgA94u5h/Fkd6T0cW1ankCSIMP90tZcwE2YS3ba9I5S1S8v0ao=
env:
  global:
  - secure: QJzHjhPwG0nQ9/m3y+xRTJ2S4N08v2SVTjlrw3Cvf8Ja55LKsFlXf/1T40WIVba7IQKPsUiSBxDPBjRoXltJj7ZRCVfm3ZW3BFKVyGzswNQOwPraxNCq1aNRMNpW8OQggN94Rn+g641iBWkHhfnLL7yqv1phNi1jFpFfwhhUA4A=
  - secure: LpxNv01FUNMjNcCgmTaPG6xa8T+GeTG6NPGpcUniDvlK1u+CkCE60Z/OLqBtxTQ6OfcEPTky1nc0wWpcMXz8saiTycKOo1AEXuP0x+J2YGozjQvfnO2rEUM8l+ts+h6Zt+gewzQB5/XKQ6uAIANs07d4/ydXbJjT7QGMVbuOnIs=
