version: '3'
services:
  openvas:
    build: ./base
    image: mikesplain/openvas
    hostname: openvas
    expose:
      - "443"
    volumes:
    - redis:/var/run/redis
    environment:
      # CHANGE THIS !
      OV_PASSWORD: admin
  redis:
    image: redis:4.0-stretch
    volumes:
    - ./base/config/redis.config.compose:/etc/redis/redis.config
    - redis:/var/run/redis
    command: /etc/redis/redis.config
    entrypoint: redis-server

volumes:
  redis: